# Default configuration for Zero Waste Data Cleaning Pipeline

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_dir: logs
  file_name: pipeline.log
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Data paths
data:
  raw_dir: data/raw
  processed_dir: data/processed
  input_file: zero_waste.csv
  output_file: cleaned_data.csv

# Text processing
text_processing:
  min_text_length: 10
  remove_urls: true
  remove_html: true
  preserve_usernames: true
  language: en
  stopwords_language: english

# Model parameters
models:
  anomaly_detection:
    algorithm: isolation_forest
    contamination: 0.1
  clustering:
    algorithm: dbscan
    eps: 0.5
    min_samples: 5
  text_embedding:
    model: tfidf
    max_features: 10000

# Performance monitoring
performance:
  enable_monitoring: true
  alert_thresholds:
    memory_usage: 0.9
    cpu_usage: 0.8
    execution_time: 300

# Cache settings
cache:
  enable: true
  directory: cache
  max_size_mb: 1024
  ttl_seconds: 86400  # 24 hours
